########################### 索引统计相关配置 begin ###########################
# 全平台集群数量统计指标中上限
es.metrics.cluster.buckets.max.num: 5000
# 单集群获取统计指标中节点数量上限
es.metrics.nodes.buckets.max.num: 5000
# 单集群获取统计指标中索引数量上限
es.metrics.indices.buckets.max.num: 10000

########################### 索引统计相关配置 end ###########################


default.query.limit: 800
delay.delete.expired.template.time: now-1d
history.query.time: now-93d
scroll.timeout: 60s
recent.create.field.day.count: 7

# spring 公共配置
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8
  profiles:
    active: test

# admin server http port
admin:
  port:
    web: 8010
  contextPath: /admin/api

# 事务超时时间
spring.transaction.default-timeout: 60

server:
  servlet:
    session:
      cookie:
        path: /

# 扩展服务
extend:
  service:
  fileStorage: s3
  department: defaultDep
  employee: defaultEmployee
  loginProtocol: defaultLogin
#extend.service: capacityPlan,dynamicLimit

# dcdr相关
# 并发执行数
dcdr.concurrent: 2
# 容错数
dcdr.fault.tolerant: 5

# 集成测试相关配置
integrate:
  test:
    # admin服务，填写本地ip，则运行集成测试前，需启动admin服务
    admin:
      ip: 127.0.0.1
      port: 8010
    # es服务，作为基本的物理集群使用
    es:
      ip: 10.190.55.161
      port: 8888
    # appid信息
    appid: 1
    # 填写管理员name
    operator: admin