name: 3_test
stages:
  - name: 编译打包
    jobs:
      - name: compile-job-centos7.2
        tasks:
          - name: compile-task
            type: oe-compile
            params:
              image: true
              osType: centos7.2
              env: test
  - name: deploy-container
    trigger: manual
    jobs:
      - name: deploy-container-job
        tasks:
          - name: deploy-container
            type: oe-deploy:test
            params:
              flavor: T4
              port: 8080
              replicas: 1
              domain: 1
              region: zjy02
            variables:
              env: test
