name: arius-admin-v2
stages: 
    - name: Compile-test
      jobs: 
        - name: compile-job-test
          tasks: 
            - name: compile-test
              type: oe-compile
              params: 
                image: true
                osType: centos7.2
                env: test
    - name: Deploy-test
      jobs: 
        - name: deploy-job-test
          tasks: 
            - name: deploy-test
              type: oe-deploy:test
              params: 
                flavor: S2
                port: 8080
                replicas: 1
                domain: http://api-kylin-xg02.intra.xiaojukeji.com/bigdata_databus_arius_admin_v2_test_test
                region: zjy02
            - name: 未命名串行子任务
              type: oe-compile
              params: 
                osType: centos6.7
