name: arius-admin-v2
stages: 
    - name: Compile-stable
      jobs:
        - name: compile-job-stable
          tasks:
            - name: compile-stable
              type: oe-compile
              params:
                image: true
                osType: centos7.2
                env: stable
    - name: Deploy-stable
      jobs:
        - name: deploy-job-stable
          tasks:
            - name: deploy-stable
              type: oe-deploy:stable
              params:
                flavor: T4
                port: 8080
                replicas: 1
                env: stable
                region: zjy02
